In [1]:
import pandas as pd

In [2]:
url = "https://en.wikipedia.org/wiki/List_of_NBA_champions"

In [3]:
dfs = pd.read_html(url)

In [33]:
df = dfs[1].copy()
df.drop(0,inplace = True)
df.drop(4, inplace = True)
df.reset_index(drop=True , inplace = True)
df.head()

,Year,Western champion,Coach,Result,Eastern champion,Coach.1,Reference
0,1947,"Chicago Stags (1) (1, 0–1)",Harold Olsen,1–4,"Philadelphia Warriors (2) (1, 1–0)",Eddie Gottlieb,[17]
1,1948,"Baltimore Bullets (2) (1, 1–0)",Buddy Jeannette,4–2,"Philadelphia Warriors (1) (2, 1–1)",Eddie Gottlieb,[18]
2,1949,"Minneapolis Lakers (2) (1, 1–0)",John Kundla,4–2,"Washington Capitols (1) (1, 0–1)",Red Auerbach,[19]
3,1950,"Minneapolis Lakers (1) [a] (2, 2–0)",John Kundla,4–2,"Syracuse Nationals (1) (1, 0–1)",Al Cervi,[23][24]
4,1951,"Rochester Royals (2) (1, 1–0)",Les Harrison,4–3,"New York Knicks (3) (1, 0–1)",Joe Lapchick,[25]

In [34]:
df["champ_conf"] = df.Result.apply(lambda result : "W" if result.split("–")[0]  > result.split("–")[-1] else "E")
df["champ"] = df.apply(lambda row : row["Western champion"] if row.champ_conf == "W" else row["Eastern champion"]  ,axis = 1 )
df["champ"] = df.champ.apply(lambda c : c.split("(")[0].strip())
df["Year"] = df.Year.apply(lambda y: y[:4])
df["Year"] = df.Year.astype('int64')
df = df[df.Year >= 1997].reset_index(drop=True)      
df

,Year,Western champion,Coach,Result,Eastern champion,Coach.1,Reference,champ_conf,champ
0,1997,"Utah Jazz (1) (1, 0–1)",Jerry Sloan,2–4,"Chicago Bulls (1) (5, 5–0)",Phil Jackson,[73],E,Chicago Bulls
1,1998,"Utah Jazz (1) (2, 0–2)",Jerry Sloan,2–4,"Chicago Bulls (1) (6, 6–0)",Phil Jackson,[74],E,Chicago Bulls
2,1999,"San Antonio Spurs (1) (1, 1–0)",Gregg Popovich,4–1,"New York Knicks (8) (8, 2–6)",Jeff Van Gundy,[76],W,San Antonio Spurs
3,2000,"Los Angeles Lakers (1) (25, 12–13)",Phil Jackson,4–2,"Indiana Pacers (1) (1, 0–1)",Larry Bird,[77],W,Los Angeles Lakers
4,2001,"Los Angeles Lakers (2) (26, 13–13)",Phil Jackson,4–1,"Philadelphia 76ers (1) (9, 3–6)",Larry Brown,[78],W,Los Angeles Lakers
5,2002,"Los Angeles Lakers (3) (27, 14–13)",Phil Jackson,4–0,"New Jersey Nets (1) (1, 0–1)",Byron Scott,[79],W,Los Angeles Lakers
6,2003,"San Antonio Spurs (1) (2, 2–0)",Gregg Popovich,4–2,"New Jersey Nets (2) (2, 0–2)",Byron Scott,[80],W,San Antonio Spurs
7,2004,"Los Angeles Lakers (2) (28, 14–14)",Phil Jackson,1–4,"Detroit Pistons (3) (6, 3–3)",Larry Brown,[81],E,Detroit Pistons
8,2005,"San Antonio Spurs (2) (3, 3–0)",Gregg Popovich,4–3,"Detroit Pistons (2) (7, 3–4)",Larry Brown,[82],W,San Antonio Spurs
9,2006,"Dallas Mavericks (4) (1, 0–1)",Avery Johnson,2–4,"Miami Heat (2) (1, 1–0)",Pat Riley,[83],E,Miami Heat
10,2007,"San Antonio Spurs (3) (4, 4–0)",Gregg Popovich,4–0,"Cleveland Cavaliers (2) (1, 0–1)",Mike Brown,[84],W,San Antonio Spurs
11,2008,"Los Angeles Lakers (1) (29, 14–15)",Phil Jackson,2–4,"Boston Celtics (1) (20, 17–3)",Doc Rivers,[85],E,Boston Celtics
12,2009,"Los Angeles Lakers (1) (30, 15–15)",Phil Jackson,4–1,"Orlando Magic (3) (2, 0–2)",Stan Van Gundy,[86],W,Los Angeles Lakers
13,2010,"Los Angeles Lakers (1) (31, 16–15)",Phil Jackson,4–3,"Boston Celtics (4) (21, 17–4)",Doc Rivers,[87],W,Los Angeles Lakers
14,2011,"Dallas Mavericks (3) (2, 1–1)",Rick Carlisle,4–2,"Miami Heat (2) (2, 1–1)",Erik Spoelstra,[88],W,Dallas Mavericks
15,2012,"Oklahoma City Thunder (2) (4, 1–3)",Scott Brooks,1–4,"Miami Heat (2) (3, 2–1)",Erik Spoelstra,[91],E,Miami Heat
16,2013,"San Antonio Spurs (2) (5, 4–1)",Gregg Popovich,3–4,"Miami Heat (1) (4, 3–1)",Erik Spoelstra,[92],E,Miami Heat
17,2014,"San Antonio Spurs (1) (6, 5–1)",Gregg Popovich,4–1,"Miami Heat (2) (5, 3–2)",Erik Spoelstra,[93],W,San Antonio Spurs
18,2015,"Golden State Warriors (1) (7, 4–3)",Steve Kerr,4–2,"Cleveland Cavaliers (2) (2, 0–2)",David Blatt,[94],W,Golden State Warriors
19,2016,"Golden State Warriors (1) (8, 4–4)",Steve Kerr,3–4,"Cleveland Cavaliers (1) (3, 1–2)",Tyronn Lue,[95],E,Cleveland Cavaliers
20,2017,"Golden State Warriors (1) (9, 5–4)",Steve Kerr,4–1,"Cleveland Cavaliers (2) (4, 1–3)",Tyronn Lue,[96],W,Golden State Warriors
21,2018,"Golden State Warriors (2) (10, 6–4)",Steve Kerr,4–0,"Cleveland Cavaliers (4) (5, 1–4)",Tyronn Lue,[97],W,Golden State Warriors
22,2019,"Golden State Warriors (1) (11, 6–5)",Steve Kerr,2–4,"Toronto Raptors (2) (1, 1–0)",Nick Nurse,[98],E,Toronto Raptors
23,2020,"Los Angeles Lakers (1) (32, 17–15)",Frank Vogel,4–2,"Miami Heat (5) (6, 3–3)",Erik Spoelstra,[100],W,Los Angeles Lakers
24,2021,"Phoenix Suns (2) (3, 0–3)",Monty Williams,2–4,"Milwaukee Bucks (3) (3, 2–1)",Mike Budenholzer,[101],E,Milwaukee Bucks
25,2022,"Golden State Warriors (3) (12, 7–5)",Steve Kerr,4–2,"Boston Celtics (2) (22, 17–5)",Ime Udoka,[102],W,Golden State Warriors

In [35]:
df = df.groupby("champ").Year.count().reset_index().sort_values(by="Year" , ascending = False).reset_index(drop=True)
df.to_csv("champs.csv")
df

                    champ  Year
0      Los Angeles Lakers     6
1       San Antonio Spurs     5
2   Golden State Warriors     4
3              Miami Heat     3
4           Chicago Bulls     2
5          Boston Celtics     1
6     Cleveland Cavaliers     1
7        Dallas Mavericks     1
8         Detroit Pistons     1
9         Milwaukee Bucks     1
10        Toronto Raptors     1